[k8s_master]
hpe16.anuket.iol.unh.edu ansible_user=agnikmisra ansible_ssh_private_key_file=~/Desktop/drona ansible_become=yes

[k8s_master:vars]
k8s_version=1.28.0
target_user=agnikmisra
ansible_ssh_pass=1234

[smo_servers]
smo-node-1 ansible_host=hpe16.anuket.iol.unh.edu ansible_user=agnikmisra ansible_ssh_private_key_file=~/Desktop/drona ansible_ssh_pass=1234

[smo_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
ansible_become_method=sudo
ansible_become_password=1234
ansible_ssh_pass=1234
storage_class=smo-storage
